name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    permissions:
      id-token: write
      actions: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate as Move Industries Bot
        uses: actions/create-github-app-token@v1
        id: authenticate
        with:
          app-id: ${{ vars.MOVE_INDUSTRIES_BOT_APP_ID }}
          private-key: ${{ secrets.MOVE_INDUSTRIES_BOT_APP_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish-packages
        env:
          GITHUB_TOKEN: ${{ steps.authenticate.outputs.token }}
          NPM_CONFIG_PROVENANCE: true
